language: python

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
      sudo: required
    - python: 3.6
    - python: 3.5
    - python: 3.4
    - python: 2.7

sudo: false

install:
 - pip install pyflakes pycodestyle
 - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install black; fi

script:
 # Static analysis
 - pyflakes .
 - pycodestyle --statistics --count .
 - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then black --check --diff .; fi
