language: python

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
python:
 - "pypy3"
 - "pypy"
 - "2.7"
 - "3.6"
 - "3.5"
 - "3.4"

sudo: false

install:
 - pip install pyflakes pycodestyle
 - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install black flake8; fi

script:
 # Static analysis
 - pyflakes .
 - pycodestyle --statistics --count .
 - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then black --check --diff .; fi

matrix:
  fast_finish: true
